### ISSUE TITLE
.caffemodel files are missing

### ISSUE THREAD

**Issue by syagev** [lugiavn/gt-crossview#1]
It seems like the intention was to include your trained models for testing and comparison however I cannot find them in this repo or in the downloadable data files. Am I missing something? Thanks.

**Comment by lugiavn** [comment]
Hello, the model is kind of big so it's not in this repo, I'll try uploading it somewhere else (however you should be able to obtain the model by running the training with caffe)

**Comment by syagev** [comment]
Thanks, I think dropbox will give you 2gb on the free tier so can be a good option. Also, mediafire hosting the data seems to do a good job :)
I'll try reproducing the results but I only have a single modest machine so I'm worried it'll take a very long while. Can you please specify what was fhe hardware you used for training and how long ot took? (Couldn't find it in the paper). Thanks!

**Comment by lugiavn** [comment]
This might be that model file: http://www.mediafire.com/file/cthi6iizyh9a0t1/2_iter_80000.caffemodel
I'm not 100% sure because I don't keep track of my old data. caffe data layer mean value = 100

I used a Titan X. I think it took less than 2 days.

**Comment by syagev** [comment]
Cool. Thanks.
